### ISSUE TITLE
Mein Projekt hinzufügen "Jack The Runner"

### ISSUE THREAD

**Issue by fixxiefixx** [gppcc/gppcc8#1]
Ich würde mich freuen wenn Ihr mein Projekt "Jack The Runner" in eure Projektliste aufnehmen würdet:
Source Code: https://github.com/fixxiefixx/fixxiefixx.github.io/tree/master/JackDanger
Ausprobieren: https://fixxiefixx.github.io/JackDanger/

**Comment by zhedar** [comment]
Gerne, du kannst übrigens jedes Projekt auch über GitHub Pages hosten, indem du einen Branch `gh-pages` in deinem Projekt erstellst. Jegliche Fortschritte dort drin sind dann wie über deine eigene Pages-Seite (die für deinen Account momentan) auch online gehostet. Dadurch musst du nicht deine persönliche Seite für ein Projekt opfern ;)

**Comment by zhedar** [comment]
Hinzugefügt in bc8f84458aaeeda475091a5c7e8de97139801d3c , falls sich an den Links was ändern sollte, gib einfach nochmal Bescheid.
